### ISSUE TITLE
'/home3/HWGroup/zhengrc/HCC2021/Train'

### ISSUE THREAD

**Issue by MurtazaAbdissamat** [ZIC-skyzrc/HCC-segmentation#1]
runfile('C:/Users/Admin/Desktop/HCC-segmentation-main/Data_prepropcess.py', wdir='C:/Users/Admin/Desktop/HCC-segmentation-main')
Traceback (most recent call last):

  File "C:\Users\Admin\Desktop\HCC-segmentation-main\Data_prepropcess.py", line 136, in <module>
    create_train_data()

  File "C:\Users\Admin\Desktop\HCC-segmentation-main\Data_prepropcess.py", line 49, in create_train_data
    dirs = sorted(os.listdir(data_path))

FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: '/home3/HWGroup/zhengrc/HCC2021/Train'

**Comment by ZIC-skyzrc** [comment]
This is the path of the training data, with each patient as a subfolder containing four phase of DCE images as well as labels for liver and HCC （i.e., four phases: co_dyn1.nii, co_dyn2.nii, co_dyn3.nii,co_dyn4.nii; liver mask: l_new.nii; tumor mask: t_new.nii）.We are sorry that we cannot disclose all the image data due to privacy issues, we recommend you to try with some other data, welcome to exchange, thanks.


-----原始邮件-----
发件人:Murtaza ***@***.***>
发送时间:2023-01-04 15:41:29 (星期三)
收件人: ZIC-skyzrc/HCC-segmentation ***@***.***>
抄送: Subscribed ***@***.***>
主题: [ZIC-skyzrc/HCC-segmentation] '/home3/HWGroup/zhengrc/HCC2021/Train' (Issue #1)



runfile('C:/Users/Admin/Desktop/HCC-segmentation-main/Data_prepropcess.py', wdir='C:/Users/Admin/Desktop/HCC-segmentation-main')
Traceback (most recent call last):

File "C:\Users\Admin\Desktop\HCC-segmentation-main\Data_prepropcess.py", line 136, in
create_train_data()

File "C:\Users\Admin\Desktop\HCC-segmentation-main\Data_prepropcess.py", line 49, in create_train_data
dirs = sorted(os.listdir(data_path))

FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: '/home3/HWGroup/zhengrc/HCC2021/Train'

**Comment by reetz145** [comment]
Respected Sir,
Is it possible to provide MRI images required for segmentation as I am currently working on the aspect. Your help will be highly appreciated.
Regards,
Reetam.
